GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info/

###
GET http://localhost:3001/api/persons/677a01b5a2d2a3fb13e1e724

###
DELETE http://localhost:3001/api/persons/677b51b5a2d2a3fb13e1e724

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{ 
    "name": "Arto Kallc", 
    "number": "040-123456"
}

###
GET https://fs-open-revised-backend.onrender.com/api/persons